### ISSUE TITLE
Suggestion for Config file

### ISSUE THREAD

**Issue by OfficialAnvie** [JustPlayerDE/justplayer-tpa#4]
Hi dev, i had for you a suggest. Please made command for reload config mading full reload/restart on big servers can made long lag or crash a server. I like your's plugin but please add it i will be happy for that option.

**Comment by justinkluever** [comment]
Thanks for your suggestion, I will implement the reload command as soon as I am able to ^^

**Comment by justinkluever** [comment]
I was able to implement this sooner than expected. You can download a version with the reload command [here](https://github.com/JustPlayerDE/justplayer-tpa/releases/tag/latest-dev).
Please note that this is not a stable release though.
